version: '3.3'

services:

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  project:
    container_name: ghalam
    build:
       context: '.'
       dockerfile: "./Dockerfile"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
